--AGE_VENDUTO_CLIENTE
SELECT        
	TOP (100) PERCENT COD_AGENTE, COD_CLI, SUM(VALORE_VENDITA) AS VENDUTO_TOT_CLIENTE
FROM            
	VENDITE_MASTER
GROUP BY COD_CLI, COD_AGENTE
ORDER BY COD_AGENTE, VENDUTO_TOT_CLIENTE DESC