--AGE_CLIENTE_CALCOLO_PERC
SELECT        
	TOP (100) PERCENT AGE_VENDUTO_COMPLESSIVO.VENDUTO_AGE, AGE_VENDUTO_CLIENTE.COD_CLI, AGE_VENDUTO_CLIENTE.VENDUTO_TOT_CLIENTE, 
	AGE_VENDUTO_CLIENTE.VENDUTO_TOT_CLIENTE / AGE_VENDUTO_COMPLESSIVO.VENDUTO_AGE * 100 AS PERC, AGE_VENDUTO_COMPLESSIVO.COD_AGENTE
FROM            
	AGE_VENDUTO_COMPLESSIVO INNER JOIN
    AGE_VENDUTO_CLIENTE ON AGE_VENDUTO_COMPLESSIVO.COD_AGENTE = AGE_VENDUTO_CLIENTE.COD_AGENTE
ORDER BY PERC DESC