--ARTICOLO_CALCOLO_PERC
SELECT        
	TOP (100) PERCENT MARGINE_ARTICOLO.COD_ARTI, MARGINE_ARTICOLO.MARGINE_TOT_VENDITE, MARGINE_COMPLESSIVO.MARGINE_TOT, 
    MARGINE_ARTICOLO.MARGINE_TOT_VENDITE /CASE WHEN MARGINE_COMPLESSIVO.MARGINE_TOT > 0 then MARGINE_COMPLESSIVO.MARGINE_TOT else 1 end  * 100 AS PERC
FROM            
	MARGINE_ARTICOLO CROSS JOIN
    MARGINE_COMPLESSIVO
ORDER BY PERC DESC