--articolo_margine_e_qta_complessivo_per_calcolo_percentuale
SELECT        
	COD_ARTI, CASE DISTRIB WHEN 'N' THEN [VALORE VENDITA] / [QTA VENDITA] * 0.77 ELSE [VALORE VENDITA] / [QTA VENDITA] END AS VENDITA_MEDIA, 
    CASE DISTRIB WHEN 'N' THEN MARGINE / [QTA VENDITA] * 0.77 ELSE MARGINE / [QTA VENDITA] END AS [MARGINE MEDIO], [QTA VENDITA]
FROM            
	[ARTICOLI_STAMPA_COMPLESSIVA_VENDITA_PER ARTICOLO]