--ULTIMI_TRE_MESI
SELECT        
	$SIGLAAZIE$MMA_D.CKY_ART, SUM($SIGLAAZIE$MMA_D.NQT_MOVM_UM1) / 3 AS ULTIMI_TRE_MESI
FROM            
	$SIGLAAZIE$MMA_D INNER JOIN
    $SIGLAAZIE$MMA_M ON $SIGLAAZIE$MMA_D.ANNO = $SIGLAAZIE$MMA_M.ANNO AND $SIGLAAZIE$MMA_D.CSG_DOC = $SIGLAAZIE$MMA_M.CSG_DOC AND 
    $SIGLAAZIE$MMA_D.CKY_SAZ_DOC = $SIGLAAZIE$MMA_M.CKY_SAZ_DOC AND $SIGLAAZIE$MMA_D.NGB_SR_DOC = $SIGLAAZIE$MMA_M.NGB_SR_DOC AND $SIGLAAZIE$MMA_D.NGL_DOC = $SIGLAAZIE$MMA_M.NGL_DOC AND
    $SIGLAAZIE$MMA_D.CKY_CNT_CLFR = $SIGLAAZIE$MMA_M.CKY_CNT_CLFR AND $SIGLAAZIE$MMA_D.NPR_DOC = $SIGLAAZIE$MMA_M.NPR_DOC AND 
    $SIGLAAZIE$MMA_D.NGB_ANNO_DOC = $SIGLAAZIE$MMA_M.NGB_ANNO_DOC
WHERE        
	(DATEDIFF(month, $SIGLAAZIE$MMA_M.DTT_DOC, GETDATE()) >= 0) AND ($SIGLAAZIE$MMA_D.CSG_DOC = 'BC' OR
    $SIGLAAZIE$MMA_D.CSG_DOC = 'FT' OR
    $SIGLAAZIE$MMA_D.CSG_DOC = 'FC') AND (DATEDIFF(month, $SIGLAAZIE$MMA_M.DTT_DOC, GETDATE()) <= 2)
GROUP BY $SIGLAAZIE$MMA_D.CKY_ART