--VENDITE_MASTER
SELECT        
	$SIGLAAZIE$MMA_M.ANNO, $SIGLAAZIE$MMA_M.DTT_DOC AS DATA, $SIGLAAZIE$MMA_M.CSG_DOC AS SIGLA, $SIGLAAZIE$MMA_M.NGB_SR_DOC AS SERIE, $SIGLAAZIE$MMA_M.NGL_DOC AS NUMERO, 
    $SIGLAAZIE$MMA_M.CKY_CNT_CLFR AS COD_CLI, $SIGLAAZIE$RUDT_1.CDS_CNT_RAGSOC AS RAG_SOC, $SIGLAAZIE$MMA_M.CDS_TP_PRG_MAG, $SIGLAAZIE$MMA_M.NKY_CAUM AS CAUSALE, 
    $SIGLAAZIE$MMA_M.NKY_DEP AS MAGAZZINO, $SIGLAAZIE$PICO.CKY_CNT_AGENTE AS COD_AGENTE, $SIGLAAZIE$RUDT.CDS_CNT_RAGSOC AS RAG_SOC_AGENTE, $SIGLAAZIE$MMA_D.CKY_ART AS COD_ARTI, 
    $SIGLAAZIE$ARTI.CDS_ART AS DESCRIZIONE_ARTI, $SIGLAAZIE$ARTI.IST_ART AS TIPO_ARTI, $SIGLAAZIE$ARTI.NMP_UCA AS ULTIMO_COSTO_ANAGR_ARTI, $SIGLAAZIE$MMA_D.NQT_MOVM_UM1 AS QTA_VENDITA, 
    $SIGLAAZIE$MMA_D.NMP_VALMOV_UM1 AS VALORE_VENDITA, $SIGLAAZIE$MMA_D.NMP_VALSCT_UM1 AS VALORE_SCONTO, $SIGLAAZIE$MMA_D.CSG_SCO_UNO AS SCO1, $SIGLAAZIE$MMA_D.CSG_SCO_DUE AS SCO2, 
    $SIGLAAZIE$MMA_D.CSG_SCO_TRE AS SCO3, $SIGLAAZIE$MMA_D.CSG_SCO_QUA AS SCO4, $SIGLAAZIE$MMA_D.CSG_SCO_CIN AS SCO5, $SIGLAAZIE$MMA_D.CSG_SCO_SEI AS SCO6, 
    $SIGLAAZIE$MMA_D.CSG_SCO_SET AS SCO7, $SIGLAAZIE$MMA_D.CSG_SCO_OTT AS SC08, $SIGLAAZIE$MMA_D.CSG_SCO_NOV AS SCO9, $SIGLAAZIE$MMA_D.CSG_SCO_VAL AS SCOVAL, 
    $SIGLAAZIE$MMA_D.NPC_PROVV AS PERC_PROV, $SIGLAAZIE$MMA_D.NMP_VALPRO_UM1 AS VALORE_PROVV, 
    $SIGLAAZIE$MMA_D.NMP_VALMOV_UM1 - $SIGLAAZIE$MMA_D.NMP_UCA * $SIGLAAZIE$MMA_D.NQT_MOVM_UM1 AS MARGINE, $SIGLAAZIE$MMA_D.NGB_IVA, 
    $SIGLAAZIE$MMA_D.NMP_VALMOV_UM1 * $SIGLAAZIE$MMA_D.NGB_IVA / 100 + $SIGLAAZIE$MMA_D.NMP_VALMOV_UM1 AS IVATO, $SIGLAAZIE$TPAGAM_ANAPAG.CDS_PAG AS pagamento, 
    $SIGLAAZIE$MMA_M.NMP_SPESPE AS spese_trasporto, $SIGLAAZIE$MMA_M.IST_SPESPE AS [tipo trasporto], $SIGLAAZIE$MMA_M.NMP_SP_BANCA AS spese_banca, $SIGLAAZIE$PICO.CKY_CNT_AGENTE, 
    $SIGLAAZIE$ARTI.CSG_CAT_STAT_ART, $SIGLAAZIE$ARTI.NGB_CAT_STAT_ART, MONTH($SIGLAAZIE$MMA_M.DTT_DOC) AS MESE, DATEDIFF(month, $SIGLAAZIE$MMA_M.DTT_DOC, GETDATE()) AS Expr1, 
    $SIGLAAZIE$RUDT_1.IFL_CNT_ANN, $SIGLAAZIE$TPAGAM_ANAPAG.NKY_PAG
FROM            
	$SIGLAAZIE$MMA_M 
	INNER JOIN $SIGLAAZIE$MMA_D ON $SIGLAAZIE$MMA_M.ID = $SIGLAAZIE$MMA_D.ID 
	INNER JOIN $SIGLAAZIE$ARTI ON $SIGLAAZIE$MMA_D.CKY_ART = $SIGLAAZIE$ARTI.CKY_ART 
    INNER JOIN $SIGLAAZIE$TPAGAM_ANAPAG ON $SIGLAAZIE$MMA_M.NKY_PAG = $SIGLAAZIE$TPAGAM_ANAPAG.NKY_PAG 
	INNER JOIN $SIGLAAZIE$PICO ON $SIGLAAZIE$MMA_M.CKY_CNT_CLFR = $SIGLAAZIE$PICO.CKY_CNT 
	LEFT JOIN $SIGLAAZIE$TBSA ON $SIGLAAZIE$ARTI.CSG_CAT_STAT_ART = $SIGLAAZIE$TBSA.CKY_CAT_STAT_ART AND $SIGLAAZIE$ARTI.NGB_CAT_STAT_ART = $SIGLAAZIE$TBSA.NKY_CAT_STAT_ART 
	LEFT JOIN $SIGLAAZIE$RUDT ON $SIGLAAZIE$MMA_M.CKY_CNT_AGENTE = $SIGLAAZIE$RUDT.CKY_CNT 
	LEFT JOIN $SIGLAAZIE$RUDT AS $SIGLAAZIE$RUDT_1 ON $SIGLAAZIE$MMA_M.CKY_CNT_CLFR = $SIGLAAZIE$RUDT_1.CKY_CNT
WHERE        
	($SIGLAAZIE$MMA_M.CDS_TP_PRG_MAG = 's+') AND ($SIGLAAZIE$MMA_M.NKY_CAUM = 1) AND ($SIGLAAZIE$ARTI.IST_ART = 'A' OR
    $SIGLAAZIE$ARTI.IST_ART = 'S') AND ($SIGLAAZIE$MMA_D.CSG_SCO_UNO <> 100) AND (DATEDIFF(month, 
    $SIGLAAZIE$MMA_M.DTT_DOC, GETDATE()) <= 12) AND ($SIGLAAZIE$RUDT_1.IFL_CNT_ANN = 0) AND ($SIGLAAZIE$MMA_D.NQT_MOVM_UM1 > 0)